#!/usr/bin/env python3
"""Regenerate tools/MAP.md, the section map for the oversized tool files.

Run from the repo root:  python3 tools/make_map.py
Re-run after any structural change (new/moved/renamed top-level def or class).
The map exists so Claude can Read a line range instead of a 200KB file.
"""
import re, os

TARGETS = ["tools/builder_build.py", "tools/builder_api.py", "tools/builder_verify.py",
           "tools/catalog_verify.py", "tools/build_engine.py", "tools/builder_smoke.py",
           "tools/coverage.py", "tools/catalog_build.py"]

HEADER = """# tools/ section map

Auto-generated by `tools/make_map.py`. Regenerate after any structural change to these files.

**Why this exists:** `builder_verify.py` is over 200KB and `builder_api.py` is over 150KB. Reading either whole costs tens of thousands of tokens. Use this map to jump straight to a line range with Read `offset`/`limit`, or grep for the symbol name.

**Rule: never Read these files whole.**

Note: the browser-side API used to live inside `builder_build.py` as an `API_PY = r\"\"\"...\"\"\"` string, so entries for it were defs inside a string literal. Since CH-9 (2026-07-30) it is a real module, `tools/builder_api.py`, read at build time. Everything below is now ordinary module-level Python. `builder_api.py` runs in Pyodide in the browser, not in the build process.
"""

def entries(lines):
    out = []
    for i, l in enumerate(lines, 1):
        m = re.match(r'^(class|def)\s+(\w+)', l)
        if m:
            out.append((i, ("class " if m.group(1) == "class" else "def ") + m.group(2)))
        m2 = re.match(r'^\s{4}def\s+(\w+)', l)
        if m2:
            out.append((i, "    ." + m2.group(1)))
        m3 = re.match(r'^#\s*[-=#]{3,}\s*(.*)', l)
        if m3 and m3.group(1).strip():
            out.append((i, "### " + m3.group(1).strip()[:70]))
        m4 = re.match(r"^#\s{0,2}([A-Z][A-Za-z0-9 ()/,'`.-]{6,70})\s*$", l)
        if m4:
            out.append((i, "# " + m4.group(1).strip()))
    return sorted(out)

def main():
    out = [HEADER]
    for t in TARGETS:
        if not os.path.exists(t):
            continue
        lines = open(t, encoding="utf-8", errors="replace").read().split("\n")
        out.append("## `%s`  (%dKB, %d lines)\n" % (t, os.path.getsize(t) // 1024, len(lines)))
        ents = entries(lines)
        for j, (ln, name) in enumerate(ents):
            end = ents[j + 1][0] - 1 if j + 1 < len(ents) else len(lines)
            out.append("- L%d-%d `%s`" % (ln, end, name))
        out.append("")
    open("tools/MAP.md", "w", encoding="utf-8").write("\n".join(out))
    print("wrote tools/MAP.md (%d bytes)" % os.path.getsize("tools/MAP.md"))

if __name__ == "__main__":
    main()
